# Generated by Django 3.2.2 on 2021-05-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('car', 'car'), ('motorcycle', 'motorcycle')], max_length=255)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
