# Generated by Django 3.2.2 on 2021-05-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_remove_level_vehicles_set'),
        ('vehicles', '0003_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='levels.level'),
        ),
    ]
