# Generated by Django 3.2.2 on 2021-05-19 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='cars_set',
        ),
        migrations.AddField(
            model_name='level',
            name='car_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
