# Generated by Django 3.2.2 on 2021-05-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_auto_20210519_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='car_set',
            new_name='vehicles_set',
        ),
    ]
