# Generated by Django 3.2.2 on 2021-05-20 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_license_plate'),
        ('levels', '0003_rename_car_set_level_vehicles_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='vehicles_set',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='vehicles.vehicle'),
        ),
    ]
