# Generated by Django 3.2.2 on 2021-05-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_alter_level_vehicles_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='vehicles_set',
        ),
    ]
